In [2]:
 # Use train_test_split to create training and testing data
from sklearn.model_selection import train_test_split
from numpy.random import seed
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
import os
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
seed(1)

array = []

pokedex = pd.read_csv('Pokemon.csv')
pokedex.head()


y = pokedex['Legendary']
y2 = pokedex['Type 1']

X = pokedex.drop("Legendary", axis=1)
X = X.drop("#", axis=1)
X = X.drop("Name", axis=1)
X = X.drop("Type 1", axis=1)
X = X.drop("Type 2", axis=1)
X.head()

   Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0    318  45      49       49       65       65     45           1
1    405  60      62       63       80       80     60           1
2    525  80      82       83      100      100     80           1
3    625  80     100      123      122      120     80           1
4    309  39      52       43       60       50     65           1

In [3]:
# Neural Network - Type 1

scores = []
for i in range(0,50):
    X_train, X_test, y_train, y_test = train_test_split(X, y2, stratify=y2, random_state=i)
    X_scaler = StandardScaler().fit(X_train)
    X_train_scaled = X_scaler.transform(X_train)
    X_test_scaled = X_scaler.transform(X_test)
    label_encoder = LabelEncoder()

    y_train = label_encoder.fit_transform(y_train)
    y_test = label_encoder.fit_transform(y_test)

    y_train_categorical = to_categorical(y_train)
    y_test_categorical = to_categorical(y_test)
    
    model = Sequential()
    model.add(Dense(units=6, activation='relu', input_dim=8))
    model.add(Dense(units=18, activation='softmax'))
    
    model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
    
    history = model.fit(
        X_train_scaled,
        y_train_categorical,
        epochs=100,
        shuffle = True,
        verbose = 0,
        validation_data=(X_test_scaled,y_test_categorical)
    )
    model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=0)
    

    scores.append(model_accuracy)
    print('Test Acc: %.3f' % model_accuracy)

    
average = sum(scores)/len(scores)
print(average)
array.append(scores)

Test Acc: 0.225
Test Acc: 0.195
Test Acc: 0.245
Test Acc: 0.205
Test Acc: 0.285
Test Acc: 0.230
Test Acc: 0.225
Test Acc: 0.175
Test Acc: 0.215
Test Acc: 0.215
Test Acc: 0.225
Test Acc: 0.180
Test Acc: 0.215
Test Acc: 0.250
Test Acc: 0.185
Test Acc: 0.185
Test Acc: 0.200
Test Acc: 0.200
Test Acc: 0.225
Test Acc: 0.245
Test Acc: 0.235
Test Acc: 0.195
Test Acc: 0.220
Test Acc: 0.245
Test Acc: 0.165
Test Acc: 0.205
Test Acc: 0.205
Test Acc: 0.210
Test Acc: 0.180
Test Acc: 0.210
Test Acc: 0.220
Test Acc: 0.205
Test Acc: 0.220
Test Acc: 0.175
Test Acc: 0.210
Test Acc: 0.205
Test Acc: 0.190
Test Acc: 0.150
Test Acc: 0.245
Test Acc: 0.220
Test Acc: 0.205
Test Acc: 0.210
Test Acc: 0.235
Test Acc: 0.225
Test Acc: 0.240
Test Acc: 0.185
Test Acc: 0.175
Test Acc: 0.200
Test Acc: 0.230
Test Acc: 0.210
0.2109999993443489

In [4]:
#KNN - Type 1
scores = []
for i in range(0,50):
    X_train, X_test, y_train, y_test = train_test_split(X, y2, stratify=y2, random_state=i)
    X_scaler = StandardScaler().fit(X_train)
    X_train_scaled = X_scaler.transform(X_train)
    X_test_scaled = X_scaler.transform(X_test)
    knn = KNeighborsClassifier(n_neighbors=17)
    knn.fit(X_train_scaled, y_train)
    score = knn.score(X_test_scaled, y_test)
    scores.append(score)
    print('Test Acc: %.3f' % score)
average = sum(scores)/len(scores)
print(average)

array.append(scores)

Test Acc: 0.195
Test Acc: 0.185
Test Acc: 0.215
Test Acc: 0.210
Test Acc: 0.245
Test Acc: 0.205
Test Acc: 0.245
Test Acc: 0.200
Test Acc: 0.205
Test Acc: 0.180
Test Acc: 0.195
Test Acc: 0.215
Test Acc: 0.190
Test Acc: 0.190
Test Acc: 0.210
Test Acc: 0.140
Test Acc: 0.205
Test Acc: 0.210
Test Acc: 0.190
Test Acc: 0.270
Test Acc: 0.190
Test Acc: 0.195
Test Acc: 0.215
Test Acc: 0.215
Test Acc: 0.210
Test Acc: 0.210
Test Acc: 0.180
Test Acc: 0.255
Test Acc: 0.165
Test Acc: 0.185
Test Acc: 0.235
Test Acc: 0.180
Test Acc: 0.200
Test Acc: 0.195
Test Acc: 0.225
Test Acc: 0.190
Test Acc: 0.200
Test Acc: 0.195
Test Acc: 0.195
Test Acc: 0.190
Test Acc: 0.200
Test Acc: 0.170
Test Acc: 0.210
Test Acc: 0.220
Test Acc: 0.185
Test Acc: 0.205
Test Acc: 0.200
Test Acc: 0.185
Test Acc: 0.200
Test Acc: 0.225
0.2025

In [5]:
#Random Forest - Type 1
scores = []
for i in range(0,50):
    X_train, X_test, y_train, y_test = train_test_split(X, y2, stratify=y2, random_state=i)
    X_scaler = StandardScaler().fit(X_train)
    X_train_scaled = X_scaler.transform(X_train)
    X_test_scaled = X_scaler.transform(X_test)
    
    rf = RandomForestClassifier (n_estimators=300)
    rf = rf.fit(X_train, y_train)
    score = rf.score(X_test, y_test)
    
    scores.append(score)
    print('Test Acc: %.3f' % score)
average = sum(scores)/len(scores)
print(average)

array.append(scores)

Test Acc: 0.235
Test Acc: 0.270
Test Acc: 0.240
Test Acc: 0.210
Test Acc: 0.310
Test Acc: 0.235
Test Acc: 0.235
Test Acc: 0.235
Test Acc: 0.250
Test Acc: 0.245
Test Acc: 0.220
Test Acc: 0.240
Test Acc: 0.310
Test Acc: 0.325
Test Acc: 0.270
Test Acc: 0.255
Test Acc: 0.245
Test Acc: 0.230
Test Acc: 0.210
Test Acc: 0.265
Test Acc: 0.230
Test Acc: 0.210
Test Acc: 0.290
Test Acc: 0.255
Test Acc: 0.270
Test Acc: 0.270
Test Acc: 0.210
Test Acc: 0.250
Test Acc: 0.245
Test Acc: 0.230
Test Acc: 0.255
Test Acc: 0.295
Test Acc: 0.260
Test Acc: 0.275
Test Acc: 0.285
Test Acc: 0.270
Test Acc: 0.235
Test Acc: 0.270
Test Acc: 0.230
Test Acc: 0.210
Test Acc: 0.240
Test Acc: 0.230
Test Acc: 0.250
Test Acc: 0.255
Test Acc: 0.275
Test Acc: 0.220
Test Acc: 0.230
Test Acc: 0.255
Test Acc: 0.225
Test Acc: 0.300
0.2512000000000001

In [9]:
model_df = pd.DataFrame(array)

model_df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.225,0.195,0.245,0.205,0.285,0.230,0.225,0.175,0.215,0.215,...,0.205,0.21,0.235,0.225,0.240,0.185,0.175,0.200,0.230,0.210
1,0.195,0.185,0.215,0.210,0.245,0.205,0.245,0.200,0.205,0.180,...,0.200,0.17,0.210,0.220,0.185,0.205,0.200,0.185,0.200,0.225
2,0.235,0.270,0.240,0.210,0.310,0.235,0.235,0.235,0.250,0.245,...,0.240,0.23,0.250,0.255,0.275,0.220,0.230,0.255,0.225,0.300